image: python:3.7-stretch

stages:
  - package

package:obs:
  stage: package
  script:
    - apt update
    - apt -y install debhelper osc
    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
