image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.11

stages:
  - publish

package:obs_ext:
  stage: publish
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install debhelper osc tar wget
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - opsi-dev-cli -l 6 packaging obs update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
    - opsi-dev-cli changelog from-git output/
    - opsi-dev-cli release-service register-package-version opsi-server SERVER_PACKAGE --changelog-file output/changelog.md
    - opsi-dev-cli release-service push-repository-state opsi-server SERVER_PACKAGE SERVER_PACKAGE-4.3-development
  only:
    - tags

