image: python:3.7-stretch

stages:
  - package

before_script:
  - apt update
  - apt -y install debhelper osc
  - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools

package:obs_int:
  stage: package
  script:
    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:experimental

package:obs_ext:
  stage: package
  script:
    - python3 -m opsidevtools -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:experimental
