image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.11

stages:
  - publish

package:obs_int:
  stage: publish
  script:
    - opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:development
  only:
    - tags

package:obs_ext:
  stage: publish
  script:
    - opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:development
  only:
    - tags
